### ISSUE TITLE
[Issue] Design choice for identity gates

### ISSUE THREAD

**Issue by andgoldschmidt** [andgoldschmidt/pulse-simulator#12]
Identity gates are not currently included in the `MomentBuilder`, and must be added manually.

Consider the following example from notebook 12_compare-circuits.ipynb, where we are worried about identity gate crosstalk:
```Python
registers = [0, 1, 2, 3]

qr = qk.QuantumRegister(len(registers))
cr = qk.ClassicalRegister(len(registers))
circ = create_initial_state(qr, cr)
circ = second_order_Trotter_unitary(circ, Δt)

mb = ps.MomentBuilder()
my_moments = mb.build_moments(circ)
my_moments_prev = np.copy(my_moments)

# Add in explicit identity gates
for m in my_moments:
    if ps.get_moment_case(m) == "single":
        missing = [i for i in range(len(registers)) if i not in m.keys()]
        for k in missing:
            m[k] = "I1" if k % 2 == 0 else "I2"
```

**Comment by andgoldschmidt** [comment]
One issue with relying entirely on the `MomentBuilder` class is that we need to introduce identity gates during ECR gates. 

Inside `pulse_builder.py`, I got around this by using a `coloring` kwarg in `def build_pulse_schedule(...)` as well as this hacky function:
```Python
def fill_unplayed_single_qubit_gates(
    played_qubits, qubit_gates, registers, coloring, backend
):
    """
    To be run within a pulse.build block. Play identity gates on any registers that
    were not used in the moment. Use the coloring to determine the correct identity
    gate to use.

    Arguments:
        played_qubits -- the qubits that were used in the moment
        qubit_gates -- the qubit pulse shapes
        registers -- the qubits used by the simulation
        coloring -- the coloring rule for the qubits
        backend -- the Qiskit backend (for control channels)

    Returns:
        A list of the channels that were played
    """
...
   ```

I currently only use this stuff in ECR, and I require that the user fill in the pulse moment entries with desired identities for any single qubit moments.

**Comment by andgoldschmidt** [comment]
As I see it, two options exist:
1. We rely on the coloring function for all colors. This means moment builder only needs to output the type of gate (a root label, like X, SX, or ECR), and the coloring function handles type by appending the appropriate modifier.
2. We change the ECR label to include the single qubit gates, also, e.g. `{(0,1): ["ECR1", ("X1", "I1")}`.

**Comment by knsmith** [comment]
Quick question: would there ever be the chance that there's multiple IDs on the same qubit in sequential moments, followed by a 1q gate (or vice versa)? Thinking the following  ID-ID-SX. What would happen in the case where placement for the 1q gate is now a degree of freedom?

**Comment by andgoldschmidt** [comment]
Sure, this can happen. In the moment-based picture, we would always play identity gates if the qubit has not been requested by another gate. The identity gate might be the default (zero pulse) or the shaped choice, depending on that qubits color. We care about distributing identity gates _within_ a moment for crosstalk. Each moment is functionally separate.

The design freedom we do have for sequential gates is that we don't have to use the same coloring moment-to-moment. Each moment could come with its own coloring. We _might_ use this if we want to minimize the number of shaped identity gates, at the price of calibrating _all_ colors of gate on every qubit.

**Comment by epelaaez** [comment]
> The design freedom we do have for sequential gates is that we don't have to use the same coloring moment-to-moment. Each moment could come with its own coloring. We might use this if we want to minimize the number of shaped identity gates, at the price of calibrating all colors of gate on every qubit.

This point is very interesting, I think if we can figure out the scaling calibration pretty well, we could afford calibrating all colors of gate on all qubits and it would be just as costly as naively calibrating the colored gateset, but we might want to think more about this further down the line.

As for this issue, I like this option that you give:

> We rely on the coloring function for all colors. This means moment builder only needs to output the type of gate (a root label, like X, SX, or ECR), and the coloring function handles type by appending the appropriate modifier.

If I understand you correctly, we want to remove the coloring/numbering from the moment builder, and move that functionality to (maybe?) a pre-processing step when simulating our pulses.

**Comment by epelaaez** [comment]
For the ECR gate issue, we could simply modify this:

https://github.com/andgoldschmidt/pulse-simulator/blob/9505451be1ff446c6d84a85d6547892f95ec9b17/pulse_simulator/simulator.py#L161

Particularly, change this block:

```python
with qiskit.pulse.build() as pulse_moment:
        for q0, q1 in gates:
            gate_color = gates[(q0, q1)].split("_")[1]
            drive_channel = ps.get_drive_channel(q0, backend)
            control_channel = ps.get_control_channel(q0, q1, backend)
            zx_p = pulses[f"zx+_{gate_color}"]
            zx_n = pulses[f"zx-_{gate_color}"]
            x = pulses[f"x_{gate_color}"]

            # control channel is for R_ZX
            qiskit.pulse.play(zx_p, control_channel)
            qiskit.pulse.play(
                qiskit.pulse.Constant(x.duration, 0.0), control_channel
            )
            qiskit.pulse.play(zx_n, control_channel)

            # drive channel is for R_X
            qiskit.pulse.play(
                qiskit.pulse.Constant(zx_p.duration, 0.0), drive_channel
            )
            qiskit.pulse.play(x, drive_channel)
            qiskit.pulse.play(
                qiskit.pulse.Constant(zx_n.duration, 0.0), drive_channel
            )
```
to directly include the identity gate here (without having to worry about including it in the moment builder step), and use the same coloring as the zx pulse.

**Comment by andgoldschmidt** [comment]
Interesting! We have some redundant code: `pulse_builder.py`'s function `build_pulse_schedule` and `simulator.py`'s `simulate_circuit` do slightly different versions of the same thing. There are interesting advantages / disadvantages to both, probably a separate issue to talk about combining them.

> Inside `pulse_builder.py`, I got around this by using a `coloring` kwarg in `def build_pulse_schedule(...)` as well as this hacky function:

^^^In fact, the change to `_simulate_two_qubit_moment( ` that's suggested in the previous message is almost exactly what's implemented in the code I'm referencing in the above quote.

> If I understand you correctly, we want to remove the coloring/numbering from the moment builder, and move that functionality to (maybe?) a pre-processing step when simulating our pulses.

Yeah, that's kind of what the ECR solution is doing. I'll implement this and attach a new branch showing the workflow.

**Comment by epelaaez** [comment]
Sounds good! I can take a look at the new branch once that is up

**Comment by andgoldschmidt** [comment]
Merged a PR that follows _We rely on the coloring function for all colors_. See notebook  `12_compare-circuits.ipynb` for usage.

Future:
- MomentBuilder does not need to color the gate labels, only extract the gate labels.
- Simulator could wrap pulse_builder functionality. NOTE: The Simulator could be parallelized by constructing a list of schedules and simulating each separately, before multiplying together the unitaries.

**Comment by andgoldschmidt** [comment]
Breaking out issues and closing with #13
